version: 0.8.4.{build}

branches:
  only:
    - master

# cache: c:\tools\vcpkg\installed\

environment:
  matrix:
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    # PYTHON: "C:\\Miniconda36-x64"
    # PYTHON_VERSION: "3.6"
    # PYTHON_ARCH: "64"
    CMAKE_GENERATOR: Visual Studio 15 2017 Win64
    # VCPKG_DEFAULT_TRIPLET: x64-windows
    # VCPKG_x64_SHARED_ROOT: C:/tools/vcpkg/installed/x64-windows
    BOOST_LIBRARYDIR: C:\Libraries\boost_1_64_0\lib64-msvc-14.1
    CONFIGURATION: Release
    TEST1: Pylint
    TEST2: CppCheck
    TEST3: MkDocs
    # TEST4: AwesomeBot


install:
  - cmd: if [%TEST1%]==["Pylint"] pip install -r PythonClient/requirements.txt
  - cmd: if [%TEST1%]==["Pylint"] pip install pylint
  - cmd: if [%TEST3%]==["MkDocs"] pip install mkdocs
  - cmd: if [%TEST4%]==["AwesomeBot"] gem install awesome_bot
  - cmd: Setup.bat -j 8 --boost-toolset msvc-14.1
  - cmd: cd Util
  - cmd: Protoc.bat


build_script:
  - cmd: cd %APPVEYOR_BUILD_FOLDER%
  - cmd: if [%TEST1%]==["Pylint"] pylint --disable=R,C --rcfile=PythonClient/.pylintrc PythonClient/carla PythonClient/*.py
  - cmd: if [%TEST2%]==["CppCheck"] cppcheck . -iBuild -i.pb.cc --error-exitcode=1 --enable=warning --inline-suppr --quiet
  - cmd: if [%TEST3%]==["MkDocs"] mkdocs build --verbose --clean --strict --site-dir _site
  - cmd: if [%TEST4%]==["AwesomeBot"] find . -name '*.md' | xargs awesome_bot --allow-dupe --allow-redirect --skip-save-results
  - cmd: mkdir build
  - cmd: cd build
  - cmd: cmake -G"%CMAKE_GENERATOR%" ..
  - cmd: cmake --build . --config %CONFIGURATION% --target install

